# l2-rpc
server {
    listen 60001;

    location / {
        proxy_pass {{cdk_l2_rpc}};
    }
    
}

# grafana
server {
    listen 60100;

    location / {
        proxy_pass {{cdk_grafana}};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_http_version 1.1;
    }

}

# bridge-ui
server {
    listen 60200;

    location / {
        proxy_pass {{cdk_bridge_ui}};
    }

}

# bridge-service-rpc
server {
    listen 60300;

    location / {
        proxy_pass {{cdk_bridge_service_rpc}};
    }

}

# prometheus
server {
    listen 60400;

    location / {
        proxy_pass {{cdk_prometheus}};
    }
}